### ISSUE TITLE
Error with conventionalcommits preset

### ISSUE THREAD

**Issue by jscott5200** [release-it/conventional-changelog#72]
I'm new to using release-it and am playing with the bumper and conventional-changelog plugins.  I am receiving the following error and cannot find anything online about this issue.  If I switch the preset value to "angular", the release-it command runs without error.  But, when I switch back to the "conventionalcommits" preset, the error returns.  Is there a config option I'm not defining, or finding in the documention?

**.release-it.json config:**
```
{
    "git": {
        "pushArgs": ["--follow-tags", "--push-option=ci.skip"]
    },
    "gitlab": {
        "release": true
    },
    "plugins": {
        "@release-it/bumper": {
            "in": "VERSION.txt",
            "out": "VERSION.txt"
        },
        "@release-it/conventional-changelog": {
            "preset": "conventionalcommits",
            "infile": "CHANGELOG.md"
        }
    }
}
```

**installed packages:**
```
├── @angular/cli@16.2.1
├── @commitlint/cli@17.7.1
├── @commitlint/config-conventional@17.7.0
├── @release-it/bumper@5.1.0
├── @release-it/conventional-changelog@7.0.1
├── corepack@0.10.0
├── npm@8.19.1
└── release-it@16.1.5
```

**command**: `npx release-it --config .release-it.json --changelog`

**Error**
```
/usr/local/lib/node_modules/@release-it/conventional-changelog/node_modules/conventional-changelog-conventionalcommits/conventionalRecommendedBump.js:30
      if (config.preMajor && level < 2) {
                 ^

TypeError: Cannot read properties of undefined (reading 'preMajor')
    at whatBump (/usr/local/lib/node_modules/@release-it/conventional-changelog/node_modules/conventional-changelog-conventionalcommits/conventionalRecommendedBump.js:30:18)
    at /usr/local/lib/node_modules/@release-it/conventional-changelog/node_modules/conventional-recommended-bump/index.js:77:24
    at ConcatStream.<anonymous> (/usr/local/lib/node_modules/@release-it/conventional-changelog/node_modules/concat-stream/index.js:37:43)
    at ConcatStream.emit (node:events:539:35)
    at finishMaybe (/usr/local/lib/node_modules/@release-it/conventional-changelog/node_modules/readable-stream/lib/_stream_writable.js:579:14)
    at endWritable (/usr/local/lib/node_modules/@release-it/conventional-changelog/node_modules/readable-stream/lib/_stream_writable.js:594:3)
    at ConcatStream.Writable.end (/usr/local/lib/node_modules/@release-it/conventional-changelog/node_modules/readable-stream/lib/_stream_writable.js:535:22)
    at Transform.onend (node:internal/streams/readable:693:10)
    at Object.onceWrapper (node:events:641:28)
    at Transform.emit (node:events:527:28)
```

**Comment by webpro** [comment]
Does using `"preset": { "name": "conventionalcommits" }` (instead of `"preset": "conventionalcommits"`) help?

**Comment by webpro** [comment]
Great
